# Generated by Django 6.0.3 on 2026-03-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome da empresa')),
                ('description', models.TextField(verbose_name='Descrição da empresa')),
                ('email', models.EmailField(max_length=254, verbose_name='Email da empresa')),
                ('phone', models.CharField(max_length=20, verbose_name='Número de telefone')),
                ('founded_at', models.DateField(verbose_name='Data de fundação')),
            ],
            options={
                'verbose_name': 'Dados da empresa',
                'verbose_name_plural': 'Dados da empresa',
            },
        ),
    ]
